CREATE TABLE IF NOT EXISTS USERS (
	ID INT UNIQUE,
	VIDEOS TEXT, -- JSON of videos
	AUDIO TEXT -- JSON of songs downloaded (not implemented)
);
CREATE TABLE IF NOT EXISTS VIDEOS (
	ID TEXT UNIQUE, -- YT ID
	TITLE TEXT, -- the video title
	DESCRIPTION TEXT,
	CHANNEL TEXT, -- CHANNEL NAME
	CHANNEL_ID TEXT,
	YOUTUBE_DATE DATE, -- date uploaded to yt
	UPLOAD_DATE DATETIME, -- date uploaded to the website
	DURATION INT, -- LENGTH OF VIDEO IN milliseconds
	KEYWORDS TEXT, -- KEYWORDS FOR SEARCH
	CHAPTERS TEXT -- JSON of chapters
);
CREATE TABLE IF NOT EXISTS SONGS (
	ID TEXT UNIQUE,
	NAME TEXT,
	ARTISTS TEXT, -- JSON
	RELEASE_DATE TEXT,
	DURATION FLOAT, --  SECONDS
	UPLOAD_DATE DATETIME,
	SPOTIFY_ID TEXT,
	YOUTUBE_ID TEXT,
	ALBUM TEXT
)